# Generated by Django 4.1.7 on 2023-03-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Form',
        ),
    ]
