# Generated by Django 4.1.7 on 2023-03-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_rename_contact_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.additional')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.country')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notebook.form')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.position')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.organization')),
            ],
        ),
    ]
